package util

const val CLEANED_BED_SUFFIX = ".cleaned.bed"
const val SUMMITS_FILE_SUFFIX = ".summits.window150.narrowPeak"
const val SEQS_SUFFIX = ".seqs"
const val FIMO_SUFFIX = ".fimo"
const val FIMO_TSV_FILENAME = "fimo.tsv"
const val FIMO_XML_FILENAME = "fimo.xml"
const val OCCURRENCES_SUFFIX = ".occurrences.tsv"
const val TOP500_SEQS_SUFFIX = ".top500.seqs"
const val TOP500_SEQS_CENTER_SUFFIX = ".top500.seqs.center"
const val NEXT500_SEQS_SUFFIX = ".top501-1000.seqs"
const val NEXT500_SEQS_CENTER_SUFFIX = ".top501-1000.seqs.center"
const val NEXT500_SEQS_FLANK_SUFFIX = ".top501-1000.seqs.flank"
const val MEME_DIR_SUFFIX = ".top500.center.meme"
const val MEME_TXT_FILENAME = "meme.txt"
const val MEME_XML_FILENAME = "meme.xml"
const val CENTER_FIMO_DIR_SUFFIX = ".top501-1000.center.fimo"
const val FLANK_FIMO_DIR_SUFFIX = ".top501-1000.flank.fimo"
const val SHUFFLED_FIMO_DIR_SUFFIX = ".top501-1000.shuffled.fimo"
const val SHUFFLED_SEQS_SUFFIX = ".top501-1000.shuffled.seqs"
const val MOTIFS_JSON_SUFFIX = ".motifs.json"
const val EXTRA_FIMO_SUFFIX = ".extra.fimo"
